# Generated by Django 4.2.2 on 2023-07-17 10:21

from django.db import migrations, models
import django.db.models.deletion
import physics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('overlay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=150, unique=True, validators=[physics.models.validate_evenDiscipline])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('cross', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Discipline',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=150, unique=True, validators=[physics.models.validate_even])),
                ('type', models.CharField(max_length=1)),
                ('description', models.CharField(max_length=150)),
                ('base_file', models.CharField(max_length=150, verbose_name='base file')),
                ('base_commit', models.SlugField(blank=True, max_length=150, null=True, validators=[physics.models.validate_even])),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physics.discipline', verbose_name='Discipline')),
                ('overlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overlay.overlay', verbose_name='Overlay/Product')),
            ],
            options={
                'verbose_name_plural': 'Product',
                'ordering': ['name'],
            },
        ),
    ]
